# Site settings
title: Good Technology Project
description: > # this means to ignore newlines until "baseurl:"
  Research on how to do good with software
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://goodtechnologyproject.org" # the base hostname & protocol for your site
excerpt_separator: <!--more-->

permalink: /blog/:year/:month/:day/:title

disqus_username: goodtechnologyproject

# Build settings
markdown: kramdown

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      comments: true

collections:
- problems
